import type { Language } from "./translations";

export type OrganId =
  | "heart"
  | "brain"
  | "lungs"
  | "liver"
  | "kidneys"
  | "eyeball"
  | "intestine"
  | "pancreas"
  | "skin"
  | "nervous-system"
  | "muscular-system"
  | "skeleton";

export type Hotspot = {
  id: string;
  label: string;
  detail: string;
  position: [number, number, number];
  color: string;
};

export type Organ = {
  id: OrganId;
  name: string;
  scientificName: string;
  system: string;
  model: string;
  icon: string;
  accent: string;
  description: string;
  poetic: string;
  size: string;
  weight: string;
  location: string;
  function: string;
  dailyFact: string;
  medical: string;
  bloodSupply: string;
  /** A single memorable line, surfaced as the "Did you know" note. */
  funFact: string;
  tissue: string;
  comparison: string;
  conditions: string[];
  hotspots: Hotspot[];
  /** Whether `/anatomy/<id>/*.webp` illustrations exist. */
  illustrated: boolean;
};

type OrganTranslation = Omit<Organ, "id" | "model" | "icon" | "accent" | "illustrated">;

const organTranslations: Record<OrganId, Record<Language, OrganTranslation>> = {
  heart: {
    en: {
      name: "Heart",
      scientificName: "Cor",
      system: "Cardiovascular",
      description: "A muscular organ that pumps blood throughout the body, delivering oxygen and nutrients to every cell.",
      poetic: "The tireless pump",
      size: "About the size of your fist",
      weight: "250–350 g",
      location: "Behind the sternum, slightly left",
      function: "Circulates oxygenated blood",
      dailyFact: "Beats about 100,000 times",
      medical: "Its electrical rhythm coordinates every heartbeat.",
      bloodSupply: "Left and right coronary arteries",
      funFact: "It beats roughly 2.5 billion times in an average lifetime, and starts before you are born.",
      tissue: "Cardiac muscle tissue",
      comparison: "Heart vs. brain",
      conditions: ["Coronary artery disease", "Arrhythmia", "Heart valve disorders", "Heart failure", "Cardiomyopathy", "Myocarditis", "Atrial fibrillation", "Congenital heart defects"],
      hotspots: [
        { id: "aorta", label: "Aorta", detail: "Main artery", position: [-0.35, 1.65, 0.55], color: "#ee7c6a" },
        { id: "left-atrium", label: "Left Atrium", detail: "Receives oxygenated blood", position: [0.82, 0.65, 0.5], color: "#f2a33b" },
        { id: "right-atrium", label: "Right Atrium", detail: "Receives venous blood", position: [-0.9, 0.35, 0.55], color: "#6393d8" },
        { id: "left-ventricle", label: "Left Ventricle", detail: "Pumps to the body", position: [0.7, -0.75, 0.65], color: "#f2a33b" },
        { id: "right-ventricle", label: "Right Ventricle", detail: "Pumps to the lungs", position: [-0.65, -0.68, 0.66], color: "#ee7c6a" },
        { id: "mitral", label: "Mitral Valve", detail: "Prevents backflow", position: [0.18, -1.35, 0.48], color: "#d89bc4" },
      ],
    },
    de: {
      name: "Herz",
      scientificName: "Cor",
      system: "Herz-Kreislauf-System",
      description: "Ein Muskelorgan, das Blut durch den gesamten Körper pumpt und jede Zelle mit Sauerstoff und Nährstoffen versorgt.",
      poetic: "Die unermüdliche Pumpe",
      size: "Etwa so groß wie Ihre Faust",
      weight: "250–350 g",
      location: "Hinter dem Brustbein, leicht links",
      function: "Zirkuliert sauerstoffreiches Blut",
      dailyFact: "Schlägt etwa 100.000 Mal am Tag",
      medical: "Sein elektrischer Rhythmus koordiniert jeden Herzschlag.",
      bloodSupply: "Linke und rechte Kranzarterien",
      funFact: "Es schlägt ungefähr 2,5 Milliarden Mal im Laufe eines Lebens und beginnt vor der Geburt.",
      tissue: "Herzmuskelgewebe",
      comparison: "Herz vs. Gehirn",
      conditions: ["Koronare Herzkrankheit", "Arrhythmie", "Herzklappenfehler", "Herzinsuffizienz", "Kardiomyopathie", "Myokarditis", "Vorhofflimmern", "Angeborene Herzfehler"],
      hotspots: [
        { id: "aorta", label: "Hauptschlagader (Aorta)", detail: "Größte Körperarterie", position: [-0.35, 1.65, 0.55], color: "#ee7c6a" },
        { id: "left-atrium", label: "Linker Vorhof", detail: "Nimmt sauerstoffreiches Blut auf", position: [0.82, 0.65, 0.5], color: "#f2a33b" },
        { id: "right-atrium", label: "Rechter Vorhof", detail: "Nimmt venöses Blut auf", position: [-0.9, 0.35, 0.55], color: "#6393d8" },
        { id: "left-ventricle", label: "Linke Herzkammer", detail: "Pumpt in den Körperkreis", position: [0.7, -0.75, 0.65], color: "#f2a33b" },
        { id: "right-ventricle", label: "Rechte Herzkammer", detail: "Pumpt zur Lunge", position: [-0.65, -0.68, 0.66], color: "#ee7c6a" },
        { id: "mitral", label: "Mitralklappe", detail: "Verhindert den Rückfluss", position: [0.18, -1.35, 0.48], color: "#d89bc4" },
      ],
    },
    ar: {
      name: "القلب",
      scientificName: "Cor",
      system: "الجهاز الدوري",
      description: "عضو عضلي يضخ الدم في جميع أنحاء الجسم، مما يوصل الأكسجين والمغذيات لكل خلية.",
      poetic: "المضخة التي لا تكل",
      size: "حوالي حجم قبضة يدك",
      weight: "250–350 غرام",
      location: "خلف عظمة القص، مائلاً لليار قليلاً",
      function: "يدوّر الدم المحمّل بالأكسجين",
      dailyFact: "ينبض حوالي 100,000 مرة يومياً",
      medical: "ينسّق نظامه الكهربائي الذاتي كل ضربة قلب بدقة متناهية.",
      bloodSupply: "الشرايين التاجية اليسرى واليمنى",
      funFact: "ينبض حوالي 2.5 مليار مرة خلال عمر الإنسان، ويبدأ النبض قبل أن تولد.",
      tissue: "نسيج العضلة القلبية",
      comparison: "القلب مقابل الدماغ",
      conditions: ["مرض الشريان التاجي", "اضطراب نظم القلب", "أمراض صمامات القلب", "فشل القلب", "اعتلال عضلة القلب", "التهاب عضلة القلب", "الرجفان الأذيني", "عيوب القلب الخلقية"],
      hotspots: [
        { id: "aorta", label: "الشريان الأبهر", detail: "الشريان الرئيسي للجسم", position: [-0.35, 1.65, 0.55], color: "#ee7c6a" },
        { id: "left-atrium", label: "الأذين الأيسر", detail: "يستقبل الدم المؤكسج", position: [0.82, 0.65, 0.5], color: "#f2a33b" },
        { id: "right-atrium", label: "الأذين الأيمن", detail: "يستقبل الدم الوريدي", position: [-0.9, 0.35, 0.55], color: "#6393d8" },
        { id: "left-ventricle", label: "البطين الأيسر", detail: "يضخ الدم إلى كامل الجسم", position: [0.7, -0.75, 0.65], color: "#f2a33b" },
        { id: "right-ventricle", label: "البطين الأيمن", detail: "يضخ الدم إلى الرئتين", position: [-0.65, -0.68, 0.66], color: "#ee7c6a" },
        { id: "mitral", label: "الصمام المترالي", detail: "يمنع تدفق الدم العكسي", position: [0.18, -1.35, 0.48], color: "#d89bc4" },
      ],
    },
  },
  brain: {
    en: {
      name: "Brain",
      scientificName: "Encephalon",
      system: "Nervous System",
      description: "The body’s command center, integrating sensation, memory, emotion, and precise movement.",
      poetic: "The universe within",
      size: "Roughly two clenched fists",
      weight: "1.3–1.4 kg",
      location: "Protected within the skull",
      function: "Processes and coordinates signals",
      dailyFact: "Uses about 20% of the body’s energy",
      medical: "Billions of neurons communicate through electrical and chemical signals.",
      bloodSupply: "Internal carotid and vertebral arteries",
      funFact: "It has no pain receptors of its own — a headache is felt in the tissues around it.",
      tissue: "Cerebral cortex",
      comparison: "Brain vs. eye",
      conditions: ["Migraine", "Stroke", "Neurodegenerative disease", "Epilepsy", "Traumatic brain injury", "Meningitis", "Multiple sclerosis", "Brain aneurysm"],
      hotspots: [
        { id: "frontal", label: "Frontal Lobe", detail: "Planning & movement", position: [-0.7, 0.65, 0.8], color: "#ee7c6a" },
        { id: "parietal", label: "Parietal Lobe", detail: "Sensory integration", position: [0.15, 1.1, 0.65], color: "#f2a33b" },
        { id: "temporal", label: "Temporal Lobe", detail: "Memory & hearing", position: [0.75, -0.1, 0.82], color: "#6393d8" },
        { id: "cerebellum", label: "Cerebellum", detail: "Balance & coordination", position: [0.72, -0.9, 0.55], color: "#d89bc4" },
      ],
    },
    de: {
      name: "Gehirn",
      scientificName: "Encephalon",
      system: "Nervoussystem",
      description: "Das Steuerzentrum des Körpers, das Empfindungen, Gedächtnis, Emotionen und präzise Bewegungen integriert.",
      poetic: "Das Universum im Inneren",
      size: "Ungefähr zwei geballte Fäuste",
      weight: "1,3–1,4 kg",
      location: "Geschützt im Schädel",
      function: "Verarbeitet und koordiniert Signale",
      dailyFact: "Verbraucht etwa 20 % der Körperenergie",
      medical: "Milliarden von Neuronen kommunizieren über elektrische und chemische Signale.",
      bloodSupply: "Innere Halsschlagader und Wirbelarterien",
      funFact: "Es besitzt selbst keine Schmerzrezeptoren — Kopfschmerzen entstehen im umgebenden Gewebe.",
      tissue: "Großhirnrinde",
      comparison: "Gehirn vs. Auge",
      conditions: ["Migräne", "Schlaganfall", "Neurodegenerative Erkrankungen", "Epilepsie", "Schädel-Hirn-Trauma", "Meningitis", "Multiple Sklerose", "Gehirnaneurysma"],
      hotspots: [
        { id: "frontal", label: "Frontallappen", detail: "Planung & Bewegung", position: [-0.7, 0.65, 0.8], color: "#ee7c6a" },
        { id: "parietal", label: "Parietallappen", detail: "Sensorische Integration", position: [0.15, 1.1, 0.65], color: "#f2a33b" },
        { id: "temporal", label: "Temporallappen", detail: "Gedächtnis & Hören", position: [0.75, -0.1, 0.82], color: "#6393d8" },
        { id: "cerebellum", label: "Kleinhirn", detail: "Balance & Koordination", position: [0.72, -0.9, 0.55], color: "#d89bc4" },
      ],
    },
    ar: {
      name: "الدماغ",
      scientificName: "Encephalon",
      system: "الجهاز العصبي",
      description: "مركز التحكم في الجسم، حيث يدمج الإحساس والذاكرة والفيض العاطفي والحركة الدقيقة.",
      poetic: "الكون الفسيح في الداخل",
      size: "حجم قبضتي يد مضغوطتين",
      weight: "1.3–1.4 كغم",
      location: "محمي داخل الجمجمة",
      function: "يعالج ويوجه الإشارات العصبية",
      dailyFact: "يستهلك حوالي 20% من طاقة الجسم",
      medical: "تتواصل مليارات الخلايا العصبية عبر إشارات كهربائية وكيميائية.",
      bloodSupply: "الشريان السباتي الداخلي والشرايين الفقارية",
      funFact: "لا يحتوي الدماغ نفسه على مستقبلات للألم — فالصداع يحدث في الأنسجة والأوعية المحيطة به.",
      tissue: "قشرة المخ",
      comparison: "الدماغ مقابل العين",
      conditions: ["الصداع النصفي (الشقيقة)", "السكتة الدماغية", "الأمراض التنكسية العصبية", "الصرع", "إصابات الدماغ الرضية", "التهاب السحايا", "التصلب اللويحي المتعدد", "تمدد الأوعية الدموية الدماغية"],
      hotspots: [
        { id: "frontal", label: "الفص الجبهي", detail: "التخطيط والحركة", position: [-0.7, 0.65, 0.8], color: "#ee7c6a" },
        { id: "parietal", label: "الفص الجداري", detail: "التكامل الحسي", position: [0.15, 1.1, 0.65], color: "#f2a33b" },
        { id: "temporal", label: "الفص الصدغي", detail: "الذاكرة والسمع", position: [0.75, -0.1, 0.82], color: "#6393d8" },
        { id: "cerebellum", label: "المخيخ", detail: "التوازن والتنسيق الحركي", position: [0.72, -0.9, 0.55], color: "#d89bc4" },
      ],
    },
  },
  lungs: {
    en: {
      name: "Lungs",
      scientificName: "Pulmones",
      system: "Respiratory System",
      description: "Paired organs that draw in air and trade oxygen for carbon dioxide across a vast, delicate surface.",
      poetic: "The breath of life",
      size: "Each about 25 cm tall",
      weight: "About 1 kg for the pair",
      location: "Either side of the heart, within the ribcage",
      function: "Exchanges oxygen for carbon dioxide",
      dailyFact: "Moves around 11,000 L of air",
      medical: "Alveoli fold a tennis-court-sized exchange surface into the chest.",
      bloodSupply: "Pulmonary and bronchial arteries",
      funFact: "The right lung carries three lobes and the left only two, leaving a notch for the heart.",
      tissue: "Alveolar tissue",
      comparison: "Lungs vs. heart",
      conditions: ["Asthma", "COPD", "Pneumonia", "Pulmonary embolism", "Pulmonary fibrosis", "Bronchitis", "Cystic fibrosis", "Lung cancer"],
      hotspots: [
        { id: "trachea", label: "Trachea", detail: "Carries air to the lungs", position: [0, 1.6, 0.2], color: "#6393d8" },
        { id: "right-lung", label: "Right Lung", detail: "Three lobes", position: [-1.2, 0.1, 0.7], color: "#ee7c6a" },
        { id: "left-lung", label: "Left Lung", detail: "Two lobes, room for the heart", position: [1.2, 0.1, 0.7], color: "#f2a33b" },
        { id: "bronchus", label: "Bronchus", detail: "Branching airway", position: [-0.03, 0.3, 0.35], color: "#d89bc4" },
        { id: "base", label: "Lung Base", detail: "Rests on the diaphragm", position: [-1.14, -1.2, 1], color: "#7fa88a" },
      ],
    },
    de: {
      name: "Lungen",
      scientificName: "Pulmones",
      system: "Atmungssystem",
      description: "Paarige Organe, die Luft einziehen und Sauerstoff gegen Kohlendioxid auf einer riesigen, zarten Fläche austauschen.",
      poetic: "Der Atem des Lebens",
      size: "Jeweils etwa 25 cm hoch",
      weight: "Etwa 1 kg für das Paar",
      location: "Beiderseits des Herzens im Brustkorb",
      function: "Tauscht Sauerstoff gegen Kohlendioxid aus",
      dailyFact: "Bewegt etwa 11.000 L Luft täglich",
      medical: "Lungenbläschen bieten eine Austauschfläche von der Größe eines Tennisplatzes.",
      bloodSupply: "Lungen- und Bronchialarterien",
      funFact: "Die rechte Lunge hat drei Lappen und die linke zwei, um Platz für das Herz zu lassen.",
      tissue: "Alveolargewebe",
      comparison: "Lungen vs. Herz",
      conditions: ["Asthma", "COPD", "Lungenentzündung", "Lungenembolie", "Lungenfibrose", "Bronchitis", "Zystische Fibrose", "Lungenkrebs"],
      hotspots: [
        { id: "trachea", label: "Luftröhre (Trachea)", detail: "Führt Luft zu den Lungen", position: [0, 1.6, 0.2], color: "#6393d8" },
        { id: "right-lung", label: "Rechte Lunge", detail: "Drei Lungenlappen", position: [-1.2, 0.1, 0.7], color: "#ee7c6a" },
        { id: "left-lung", label: "Linke Lunge", detail: "Zwei Lappen, Platz fürs Herz", position: [1.2, 0.1, 0.7], color: "#f2a33b" },
        { id: "bronchus", label: "Bronchien", detail: "Verzweigte Atemwege", position: [-0.03, 0.3, 0.35], color: "#d89bc4" },
        { id: "base", label: "Lungenbasis", detail: "Ruht auf dem Zwerchfell", position: [-1.14, -1.2, 1], color: "#7fa88a" },
      ],
    },
    ar: {
      name: "الرئتان",
      scientificName: "Pulmones",
      system: "الجهاز التنفسي",
      description: "عضوان متجاوران يسحبان الهواء ويستبدلان الأكسجين بثاني أكسيد الكربون عبر سطح واسع ودقيق.",
      poetic: "نسمة الحياة",
      size: "ارتفاع كل منهما حوالي 25 سم",
      weight: "حوالي 1 كغم للزوجين",
      location: "على جانبي القلب داخل القفص الصدري",
      function: "تبادل الأكسجين وثاني أكسيد الكربون",
      dailyFact: "تحركان نحو 11,000 لتر من الهواء يومياً",
      medical: "تطوي الحويصلات الهوائية مساحة تبادل غازي تعادل ملعب تنيس داخل الصدر.",
      bloodSupply: "الشرايين الرئوية والقصبية",
      funFact: "تحتوي الرئة اليمنى على 3 فصوص بينما تحتوي اليسرى على فصين فقط لإتاحة المجال للقلب.",
      tissue: "نسيج الحويصلات الهوائية",
      comparison: "الرئتان مقابل القلب",
      conditions: ["الربو", "الانسداد الرئوي المزمن", "التهاب الرئة", "الانسداد الرئوي", "التليف الرئوي", "التهاب الشعب الهوائية", "التليف التكيسي", "سرطان الرئة"],
      hotspots: [
        { id: "trachea", label: "القصبة الهوائية", detail: "تنقل الهواء للرئتين", position: [0, 1.6, 0.2], color: "#6393d8" },
        { id: "right-lung", label: "الرئة اليمنى", detail: "ثلاثة فصوص رئوية", position: [-1.2, 0.1, 0.7], color: "#ee7c6a" },
        { id: "left-lung", label: "الرئة اليسرى", detail: "فصان، مساحة مخصصة للقلب", position: [1.2, 0.1, 0.7], color: "#f2a33b" },
        { id: "bronchus", label: "الشعب الهوائية", detail: "تفرعات التنفس الرئيسية", position: [-0.03, 0.3, 0.35], color: "#d89bc4" },
        { id: "base", label: "قاعدة الرئة", detail: "تستند على الحجاب الحاجز", position: [-1.14, -1.2, 1], color: "#7fa88a" },
      ],
    },
  },
  liver: {
    en: {
      name: "Liver",
      scientificName: "Hepar",
      system: "Digestive System",
      description: "A remarkable metabolic organ that filters blood, processes nutrients, and produces bile.",
      poetic: "The quiet alchemist",
      size: "About the size of a football",
      weight: "1.4–1.6 kg",
      location: "Upper right abdomen",
      function: "Metabolism, detoxification & bile",
      dailyFact: "Performs more than 500 functions",
      medical: "It can regenerate a substantial portion of lost tissue.",
      bloodSupply: "Hepatic artery and portal vein",
      funFact: "It is the only human organ that can regrow to full size from a fraction of itself.",
      tissue: "Hepatic lobules",
      comparison: "Liver vs. intestine",
      conditions: ["Fatty liver disease", "Hepatitis", "Cirrhosis", "Gallstones", "Haemochromatosis", "Liver cancer", "Autoimmune hepatitis", "Portal hypertension"],
      hotspots: [
        { id: "right-lobe", label: "Right Lobe", detail: "Largest hepatic lobe", position: [-0.75, 0.35, 0.75], color: "#ee7c6a" },
        { id: "left-lobe", label: "Left Lobe", detail: "Crosses the midline", position: [0.85, 0.25, 0.75], color: "#f2a33b" },
        { id: "portal", label: "Portal Vein", detail: "Nutrient-rich inflow", position: [0.1, -0.3, 0.82], color: "#6393d8" },
      ],
    },
    de: {
      name: "Leber",
      scientificName: "Hepar",
      system: "Verdauungssystem",
      description: "Ein bemerkenswertes Stoffwechselorgan, das Blut filtert, Nährstoffe verarbeitet und Galle produziert.",
      poetic: "Der stille Alchemist",
      size: "Etwa so groß wie ein Fußball",
      weight: "1,4–1,6 kg",
      location: "Rechter Oberbauch",
      function: "Stoffwechsel, Entgiftung & Galle",
      dailyFact: "Führt mehr als 500 Funktionen aus",
      medical: "Sie kann einen erheblichen Teil ihres Gewebes regenerieren.",
      bloodSupply: "Leberarterie und Pfortader",
      funFact: "Sie ist das einzige menschliche Organ, das aus einem Teil stückweise wieder nachwachsen kann.",
      tissue: "Leberläppchen",
      comparison: "Leber vs. Darm",
      conditions: ["Fettlebererkrankung", "Hepatitis", "Zirrhose", "Gallensteine", "Hämochromatose", "Leberkrebs", "Autoimmunhepatitis", "Portale Hypertonie"],
      hotspots: [
        { id: "right-lobe", label: "Rechter Lappen", detail: "Größter Leberlappen", position: [-0.75, 0.35, 0.75], color: "#ee7c6a" },
        { id: "left-lobe", label: "Linker Lappen", detail: "Kreuzt die Mittellinie", position: [0.85, 0.25, 0.75], color: "#f2a33b" },
        { id: "portal", label: "Pfortader", detail: "Nährstoffreicher Zufluss", position: [0.1, -0.3, 0.82], color: "#6393d8" },
      ],
    },
    ar: {
      name: "الكبد",
      scientificName: "Hepar",
      system: "الجهاز الهضمي",
      description: "عضو استقلابي رائع يصفي الدم، ويعالج المغذيات، وينتج العصارة الصفراوية.",
      poetic: "الخيميائي الصامت",
      size: "حوالي حجم كرة القدم",
      weight: "1.4–1.6 كغم",
      location: "أعلى يمين البطن",
      function: "التمثيل الغذائي، إزالة السموم والصفراء",
      dailyFact: "يقوم بأكثر من 500 وظيفة حيوية",
      medical: "يمكن للكبد تجديد جزء كبير جداً من أنسجته المتضررة بنفسه.",
      bloodSupply: "الشريان الكبدي والوريد البابي",
      funFact: "الكبد هو العضو البشري الوحيد الذي يستطيع النمو مجدداً لحجمه الكامل حتى لو تُرك جزء صغير منه.",
      tissue: "الفصيصات الكبدية",
      comparison: "الكبد مقابل الأمعاء",
      conditions: ["مرض الكبد الدهني", "التهاب الكبد الوبائي", "تليف الكبد", "حصى المرارة", "ترسب الأجسام الحديدية", "سرطان الكبد", "التهاب الكبد المناعي", "ارتفاع ضغط الوريد البابي"],
      hotspots: [
        { id: "right-lobe", label: "الفص الأيمن", detail: "أكبر فصوص الكبد", position: [-0.75, 0.35, 0.75], color: "#ee7c6a" },
        { id: "left-lobe", label: "الفص الأيسر", detail: "يعبر منتصف الجسم", position: [0.85, 0.25, 0.75], color: "#f2a33b" },
        { id: "portal", label: "الوريد البابي", detail: "تدفق غني بالمغذيات", position: [0.1, -0.3, 0.82], color: "#6393d8" },
      ],
    },
  },
  kidneys: {
    en: {
      name: "Kidneys",
      scientificName: "Renes",
      system: "Urinary System",
      description: "Paired filtration organs that balance fluids, electrolytes, blood pressure, and waste removal.",
      poetic: "The master filters",
      size: "Each is about a computer mouse",
      weight: "120–170 g each",
      location: "Either side of the spine below the ribs",
      function: "Filters blood and forms urine",
      dailyFact: "Filters roughly 180 L of fluid",
      medical: "Nephrons fine-tune the chemistry of the bloodstream.",
      bloodSupply: "Renal arteries",
      funFact: "They reclaim almost everything they filter — only about 1–2 L leaves the body as urine.",
      tissue: "Renal cortex",
      comparison: "Kidneys vs. liver",
      conditions: ["Kidney stones", "Chronic kidney disease", "Urinary infection", "Glomerulonephritis", "Polycystic kidney disease", "Renal hypertension", "Acute kidney injury", "Nephrotic syndrome"],
      hotspots: [
        { id: "cortex", label: "Renal Cortex", detail: "Outer filtering layer", position: [-0.9, 0.55, 0.7], color: "#ee7c6a" },
        { id: "medulla", label: "Renal Medulla", detail: "Concentrates urine", position: [0.85, 0.2, 0.7], color: "#f2a33b" },
        { id: "ureter", label: "Ureter", detail: "Carries urine", position: [0.4, -1.1, 0.5], color: "#6393d8" },
      ],
    },
    de: {
      name: "Nieren",
      scientificName: "Renes",
      system: "Harnsystem",
      description: "Paarige Filterorgane, die Flüssigkeiten, Elektrolyte, Blutdruck und Abfallbeseitigung regulieren.",
      poetic: "Die Meisterfilter",
      size: "Jede etwa wie eine Computermaus",
      weight: "120–170 g jeweils",
      location: "Beiderseits der Wirbelsäule unter den Rippen",
      function: "Filtert Blut und bildet Urin",
      dailyFact: "Filtert täglich rund 180 L Flüssigkeit",
      medical: "Nephrone stimmen die Chemie des Blutkreislaufs fein ab.",
      bloodSupply: "Nierenarterien",
      funFact: "Sie gewinnen fast alles zurück — nur etwa 1–2 L verlassen den Körper als Urin.",
      tissue: "Nierenrinde",
      comparison: "Nieren vs. Leber",
      conditions: ["Nierensteine", "Chronische Nierenerkrankung", "Harnwegsinfektion", "Glomerulonephritis", "Zystennieren", "Renale Hypertonie", "Akutes Nierenversagen", "Nephrotisches Syndrom"],
      hotspots: [
        { id: "cortex", label: "Nierenrinde", detail: "Äußere Filterschicht", position: [-0.9, 0.55, 0.7], color: "#ee7c6a" },
        { id: "medulla", label: "Nierenmark", detail: "Konzentriert den Urin", position: [0.85, 0.2, 0.7], color: "#f2a33b" },
        { id: "ureter", label: "Harnleiter", detail: "Leitet den Urin ab", position: [0.4, -1.1, 0.5], color: "#6393d8" },
      ],
    },
    ar: {
      name: "الكليتان",
      scientificName: "Renes",
      system: "الجهاز البولي",
      description: "عضوان مصفّيان زوجيان يوازنان السوائل والأملاح وضغط الدم وإزالة الفضلات.",
      poetic: "المرشحات الفائقة",
      size: "حجم كل منهما بحجم فارة الكمبيوتر",
      weight: "120–170 غرام لكل منهما",
      location: "على جانبي العمود الفقري أسفل الأضلاع",
      function: "تصفية الدم وتكوين البول",
      dailyFact: "تصفية حوالي 180 لتر من السوائل يومياً",
      medical: "تضبط الكليونات (النيفرونات) كيمياء مجرى الدم بدقة فائقة.",
      bloodSupply: "الشرايين الكلويّة",
      funFact: "تستعيد الكليتان تقريباً كل ما تصفيه — ويخرج نحو 1–2 لتر فقط كبول يومياً.",
      tissue: "قشرة الكلية",
      comparison: "الكليتان مقابل الكبد",
      conditions: ["حصى الكلى", "مرض الكلى المزمن", "التهاب المسالك البولية", "التهاب كبيبات الكلى", "داء الكلى المتعدد التكيسات", "ارتفاع ضغط الدم الكلوية", "فشل الكلى الحاد", "المتلازمة الكلوية"],
      hotspots: [
        { id: "cortex", label: "قشرة الكلية", detail: "طبقة الترشيح الخارجية", position: [-0.9, 0.55, 0.7], color: "#ee7c6a" },
        { id: "medulla", label: "لب الكلية", detail: "تركيز البول", position: [0.85, 0.2, 0.7], color: "#f2a33b" },
        { id: "ureter", label: "الحالب", detail: "ينقل البول إلى المثانة", position: [0.4, -1.1, 0.5], color: "#6393d8" },
      ],
    },
  },
  eyeball: {
    en: {
      name: "Eye",
      scientificName: "Oculus",
      system: "Sensory System",
      description: "A precision sensory organ that converts focused light into neural signals interpreted as vision.",
      poetic: "A window made of light",
      size: "About 24 mm across",
      weight: "Around 7.5 g",
      location: "Within the bony orbit",
      function: "Captures and focuses light",
      dailyFact: "Makes thousands of tiny movements",
      medical: "The retina is an extension of the central nervous system.",
      bloodSupply: "Ophthalmic artery",
      funFact: "The cornea carries no blood vessels at all; it takes oxygen directly from the air.",
      tissue: "Retinal layers",
      comparison: "Eye vs. brain",
      conditions: ["Myopia", "Cataract", "Glaucoma", "Macular degeneration", "Retinal detachment", "Dry eye disease", "Astigmatism", "Conjunctivitis"],
      hotspots: [
        { id: "cornea", label: "Cornea", detail: "Clear focusing surface", position: [-0.94, 0.05, 1.47], color: "#6393d8" },
        { id: "iris", label: "Iris", detail: "Controls light entry", position: [-1.22, -0.53, 1.15], color: "#f2a33b" },
        { id: "optic", label: "Optic Nerve", detail: "Carries visual signals", position: [1.61, -0.18, 0.54], color: "#d89bc4" },
      ],
    },
    de: {
      name: "Auge",
      scientificName: "Oculus",
      system: "Sinnesorgan",
      description: "Ein präzises Sinnesorgan, das fokussiertes Licht in Nervensignale umwandelt, die als Sehen interpretiert werden.",
      poetic: "Ein Fenster aus Licht",
      size: "Etwa 24 mm Durchmesser",
      weight: "Rund 7,5 g",
      location: "In der knöchernen Augenhöhle",
      function: "Erfasst und fokussiert Licht",
      dailyFact: "Macht täglich Tausende mikroskopische Bewegungen",
      medical: "Die Netzhaut ist eine direkte Verlängerung des zentralen Nervensystems.",
      bloodSupply: "Augenarterie (Arteria ophthalmica)",
      funFact: "Die Hornhaut besitzt keinerlei Blutgefäße; sie nimmt Sauerstoff direkt aus der Luft auf.",
      tissue: "Netzhautschichten",
      comparison: "Auge vs. Gehirn",
      conditions: ["Kurzsichtigkeit (Myopie)", "Grauer Star (Katarakt)", "Grüner Star (Glaukom)", "Makuladegeneration", "Netzhautablösung", "Trockenes Auge", "Hornhautverkrümmung", "Bindehautentzündung"],
      hotspots: [
        { id: "cornea", label: "Hornhaut (Cornea)", detail: "Klare Fokussierfläche", position: [-0.94, 0.05, 1.47], color: "#6393d8" },
        { id: "iris", label: "Regenbogenhaut (Iris)", detail: "Steuert den Lichteinfall", position: [-1.22, -0.53, 1.15], color: "#f2a33b" },
        { id: "optic", label: "Sehnerv", detail: "Überträgt visuelle Signale", position: [1.61, -0.18, 0.54], color: "#d89bc4" },
      ],
    },
    ar: {
      name: "العين",
      scientificName: "Oculus",
      system: "الجهاز الحسي",
      description: "عضو حسي دقيق يحول الضوء المتركز إلى إشارات عصبية تترجم إلى رؤية وصور.",
      poetic: "نافذة صُنعت من الضوء",
      size: "قطرها حوالي 24 ملم",
      weight: "حوالي 7.5 غرام",
      location: "داخل التجويف العظمي للعين (الحجاج)",
      function: "التقاط الضوء وتركيزه",
      dailyFact: "تقوم بآلاف الحركات الدقيقة يومياً",
      medical: "الشبكية هي امتداد مباشر للجهاز العصبي المركزي.",
      bloodSupply: "الشريان العيني",
      funFact: "لا تحتوي القرنية على أي أوعية دموية إطلاقاً؛ وتأخذ الأكسجين مباشرة من الهواء.",
      tissue: "طبقات الشبكية",
      comparison: "العين مقابل الدماغ",
      conditions: ["قصر النظر (الميوبيا)", "الساد (المياه البيضاء)", "الزرق (المياه الزرقاء)", "التنكس البقعي", "انفصال الشبكية", "جفاف العين", "الاستغماتيزم", "التهاب الملتحمة"],
      hotspots: [
        { id: "cornea", label: "القرنية", detail: "سطح التركيز الشفاف", position: [-0.94, 0.05, 1.47], color: "#6393d8" },
        { id: "iris", label: "القزحية", detail: "تتحكم في كمية الضوء", position: [-1.22, -0.53, 1.15], color: "#f2a33b" },
        { id: "optic", label: "العصب البصري", detail: "ينقل الإشارات البصرية للدماغ", position: [1.61, -0.18, 0.54], color: "#d89bc4" },
      ],
    },
  },
  intestine: {
    en: {
      name: "Intestine",
      scientificName: "Intestinum",
      system: "Digestive System",
      description: "A folded digestive passage where nutrients are absorbed and the microbiome supports whole-body health.",
      poetic: "The inner garden",
      size: "About 6–7 m when extended",
      weight: "Varies with contents",
      location: "Central and lower abdomen",
      function: "Digestion and nutrient absorption",
      dailyFact: "Hosts trillions of microorganisms",
      medical: "Its surface is amplified by folds, villi, and microvilli.",
      bloodSupply: "Superior and inferior mesenteric arteries",
      funFact: "Its lining renews itself every few days — the fastest turnover of any tissue in the body.",
      tissue: "Intestinal villi",
      comparison: "Intestine vs. liver",
      conditions: ["Irritable bowel syndrome", "Inflammatory bowel disease", "Celiac disease", "Diverticulitis", "Intestinal obstruction", "Colorectal polyps", "Crohn's disease", "Lactose intolerance"],
      hotspots: [
        { id: "duodenum", label: "Duodenum", detail: "First small-intestine segment", position: [0.6, 0.8, 0.75], color: "#f2a33b" },
        { id: "jejunum", label: "Jejunum", detail: "Major absorption region", position: [-0.45, 0.1, 0.82], color: "#ee7c6a" },
        { id: "colon", label: "Colon", detail: "Reclaims water", position: [0.75, -0.55, 0.72], color: "#6393d8" },
      ],
    },
    de: {
      name: "Darm",
      scientificName: "Intestinum",
      system: "Verdauungssystem",
      description: "Ein gefalteter Verdauungstrakt, in dem Nährstoffe aufgenommen werden und das Mikrobiom die Gesundheit stärkt.",
      poetic: "Der innere Garten",
      size: "Ausgestreckt etwa 6–7 m lang",
      weight: "Variiert je nach Inhalt",
      location: "Zentraler und unterer Bauchraum",
      function: "Verdauung und Nährstoffaufnahme",
      dailyFact: "Beherbergt Billionen von Mikroorganismen",
      medical: "Seine Oberfläche wird durch Falten, Zotten und Mikrozotten stark vergrößert.",
      bloodSupply: "Obere und untere Eingeweidearterie",
      funFact: "Seine Schleimhaut erneuert sich alle paar Tage — der schnellste Zellwechsel im Körper.",
      tissue: "Darmzotten",
      comparison: "Darm vs. Leber",
      conditions: ["Reizdarmsyndrom", "Chronisch-entzündliche Darmerkrankungen", "Zöliakie", "Divertikulitis", "Darmverschluss", "Darmpolypen", "Morbus Crohn", "Laktoseintoleranz"],
      hotspots: [
        { id: "duodenum", label: "Zwölffingerdarm", detail: "Erster Dünndarmabschnitt", position: [0.6, 0.8, 0.75], color: "#f2a33b" },
        { id: "jejunum", label: "Leerdarm (Jejunum)", detail: "Hauptregion der Aufnahme", position: [-0.45, 0.1, 0.82], color: "#ee7c6a" },
        { id: "colon", label: "Dickdarm (Colon)", detail: "Nimmt Wasser zurück", position: [0.75, -0.55, 0.72], color: "#6393d8" },
      ],
    },
    ar: {
      name: "الأمعاء",
      scientificName: "Intestinum",
      system: "الجهاز الهضمي",
      description: "ممر هضمي ممتد وممتلئ بالثنيات حيث تُمتص المغذيات ويدعم الميكروبيوم صحة الجسم بأكمله.",
      poetic: "الحديقة الداخلية",
      size: "حوالي 6–7 أمتار عند امتدادها",
      weight: "يختلف باختلاف المحتويات",
      location: "وسط وأسفل البطن",
      function: "الهضم وامتصاص المغذيات",
      dailyFact: "تستضيف تريليونات الكائنات الحية الدقيقة النافعة",
      medical: "تتضاعف مساحتها السطحية الهائلة بفعل الطيات والزغابات المعوية.",
      bloodSupply: "الشرايين المساريقية العلوية والسفلية",
      funFact: "تتجدد بطانة الأمعاء كل بضعة أيام — وهو أسرع معدل دوران للأنسجة في جسم الإنسان.",
      tissue: "الزغابات المعوية",
      comparison: "الأمعاء مقابل الكبد",
      conditions: ["متلازمة القولون العصبي", "داء الأمعاء الالتهابي", "داء الزلاق (حساسية القمح)", "التهاب الجيوب المعوية", "انسداد الأمعاء", "زبيبات القولون", "داء كرون", "عدم تحمل اللاكتوز"],
      hotspots: [
        { id: "duodenum", label: "الاثنا عشر", detail: "الجزء الأول من الأمعاء الدقيقة", position: [0.6, 0.8, 0.75], color: "#f2a33b" },
        { id: "jejunum", label: "الصائم", detail: "منطقة الامتصاص الرئيسية", position: [-0.45, 0.1, 0.82], color: "#ee7c6a" },
        { id: "colon", label: "القولون", detail: "يعيد امتصاص الماء السائل", position: [0.75, -0.55, 0.72], color: "#6393d8" },
      ],
    },
  },
  pancreas: {
    en: {
      name: "Pancreas",
      scientificName: "Pancreas",
      system: "Endocrine System",
      description: "A dual-purpose gland that releases digestive enzymes into the gut and the hormones that steady blood sugar.",
      poetic: "The quiet regulator",
      size: "About 15 cm long",
      weight: "70–100 g",
      location: "Behind the stomach, across the upper abdomen",
      function: "Digestive enzymes and insulin",
      dailyFact: "Makes about 1.5 L of enzyme-rich juice",
      medical: "Islets of Langerhans release insulin and glucagon to balance blood sugar.",
      bloodSupply: "Splenic and pancreaticoduodenal arteries",
      funFact: "Barely 2% of it makes hormones; the rest is given over to digestive enzymes.",
      tissue: "Pancreatic acini",
      comparison: "Pancreas vs. liver",
      conditions: ["Pancreatitis", "Type 1 diabetes", "Pancreatic cancer", "Type 2 diabetes", "Exocrine insufficiency", "Pancreatic cysts", "Gallstone pancreatitis", "Insulinoma"],
      hotspots: [
        { id: "head", label: "Head", detail: "Cradled by the duodenum", position: [-1.32, -0.36, 0.55], color: "#ee7c6a" },
        { id: "body", label: "Body", detail: "Crosses the spine", position: [0.05, 0.25, 0.45], color: "#f2a33b" },
        { id: "tail", label: "Tail", detail: "Reaches the spleen", position: [1.55, 0.3, 0.35], color: "#6393d8" },
        { id: "duct", label: "Pancreatic Duct", detail: "Drains enzymes to the gut", position: [-0.61, 0.39, 0.5], color: "#d89bc4" },
      ],
    },
    de: {
      name: "Bauchspeicheldrüse",
      scientificName: "Pancreas",
      system: "Endokrines System",
      description: "Eine Doppelfunktionsdrüse, die Verdauungsenzyme in den Darm und Hormone zur Blutzuckerregulierung abgibt.",
      poetic: "Der stille Regler",
      size: "Etwa 15 cm lang",
      weight: "70–100 g",
      location: "Hinter dem Magen im Oberbauch",
      function: "Verdauungsenzyme und Insulin",
      dailyFact: "Produziert etwa 1,5 L enzymreichen Saft",
      medical: "Langerhans-Inseln setzen Insulin und Glukagon zur Blutzuckerregulierung frei.",
      bloodSupply: "Milz- und Bauchspeicheldrüsenarterien",
      funFact: "Nur knapp 2 % produzieren Hormone; der Rest stellt Verdauungsenzyme her.",
      tissue: "Pancreas-Azini",
      comparison: "Bauchspeicheldrüse vs. Leber",
      conditions: ["Pankreatitis", "Diabetes Typ 1", "Bauchspeicheldrüsenkrebs", "Diabetes Typ 2", "Exokrine Insuffizienz", "Pankreaszysten", "Gallensteinpankreatitis", "Insulinom"],
      hotspots: [
        { id: "head", label: "Kopf", detail: "Umschlungen vom Zwölffingerdarm", position: [-1.32, -0.36, 0.55], color: "#ee7c6a" },
        { id: "body", label: "Körper", detail: "Kreuzt die Wirbelsäule", position: [0.05, 0.25, 0.45], color: "#f2a33b" },
        { id: "tail", label: "Schwanz", detail: "Reicht bis zur Milz", position: [1.55, 0.3, 0.35], color: "#6393d8" },
        { id: "duct", label: "Pankreasgang", detail: "Leitet Enzyme in den Darm", position: [-0.61, 0.39, 0.5], color: "#d89bc4" },
      ],
    },
    ar: {
      name: "البنكرياس",
      scientificName: "Pancreas",
      system: "جهاز الغدد الصماء",
      description: "غدة مزدوجة الوظيفة تفرز إنزيمات الهضم في الأمعاء والهرمونات التي تضبط مستوى السكر في الدم.",
      poetic: "المنظم الصامت",
      size: "طوله حوالي 15 سم",
      weight: "70–100 غرام",
      location: "خلف المعدة عبر أعلى البطن",
      function: "إنزيمات الهضم والأنسولين",
      dailyFact: "ينتج حوالي 1.5 لتر من العصارة الهضمية يومياً",
      medical: "تفرز جزر لانغرهانس الأنسولين والغلوكاجون لضبط نسبة السكر في الدم.",
      bloodSupply: "الشرايين الطحالية والبنكرياسية",
      funFact: "حوالي 2% فقط منه مخصص لإفراز الهرمونات؛ بينما الباقي لإفراز إنزيمات الهضم.",
      tissue: "العنيبات البنكرياسية",
      comparison: "البنكرياس مقابل الكبد",
      conditions: ["التهاب البنكرياس", "السكري من النوع الأول", "سرطان البنكرياس", "السكري من النوع الثاني", "قصور البنكرياس الخارجي", "أكياس البنكرياس", "التهاب البنكرياس الحصوي", "أورام الأنسولين"],
      hotspots: [
        { id: "head", label: "الرأس", detail: "مستقر في تجويف الاثني عشر", position: [-1.32, -0.36, 0.55], color: "#ee7c6a" },
        { id: "body", label: "الجسم", detail: "يعبر العمود الفقري", position: [0.05, 0.25, 0.45], color: "#f2a33b" },
        { id: "tail", label: "الذيل", detail: "يمتد ليصل للطحال", position: [1.55, 0.3, 0.35], color: "#6393d8" },
        { id: "duct", label: "القناة البنكرياسية", detail: "تصرف الإنزيمات للأمعاء", position: [-0.61, 0.39, 0.5], color: "#d89bc4" },
      ],
    },
  },
  skin: {
    en: {
      name: "Skin",
      scientificName: "Integumentum",
      system: "Integumentary System",
      description: "The body’s largest organ — a living barrier that senses touch, holds in water, and regulates temperature.",
      poetic: "The living boundary",
      size: "About 2 m² spread flat",
      weight: "3.5–5 kg",
      location: "Covering the entire body",
      function: "Protects, senses, and cools",
      dailyFact: "Sheds around 500 million cells",
      medical: "Three layers — epidermis, dermis, and hypodermis — each with a distinct job.",
      bloodSupply: "Dermal vascular plexus",
      funFact: "A single square centimetre can hold hundreds of sweat glands and metres of blood vessels.",
      tissue: "Epidermal layers",
      comparison: "Skin vs. intestine",
      conditions: ["Eczema", "Psoriasis", "Melanoma", "Acne vulgaris", "Cellulitis", "Contact dermatitis", "Rosacea", "Vitiligo"],
      hotspots: [
        { id: "epidermis", label: "Epidermis", detail: "Outer protective layer", position: [-0.05, 0.88, 1.4], color: "#ee7c6a" },
        { id: "dermis", label: "Dermis", detail: "Nerves, vessels & glands", position: [0.29, 0.05, 1.4], color: "#f2a33b" },
        { id: "hypodermis", label: "Hypodermis", detail: "Fat and insulation", position: [-0.39, -1.15, 1.4], color: "#6393d8" },
        { id: "follicle", label: "Hair Follicle", detail: "Anchors each hair", position: [0.89, -0.44, 1.4], color: "#d89bc4" },
      ],
    },
    de: {
      name: "Haut",
      scientificName: "Integumentum",
      system: "Hautsystem",
      description: "Das größte Organ des Körpers — eine lebendige Barriere, die Berührung spürt, Wasser zurückhält und die Temperatur reguliert.",
      poetic: "Die lebende Grenze",
      size: "Flach ausgelegt etwa 2 m²",
      weight: "3,5–5 kg",
      location: "Hüllt den gesamten Körper ein",
      function: "Schützt, fühlt und kühlt",
      dailyFact: "Stößt täglich rund 500 Millionen Zellen ab",
      medical: "Drei Schichten — Epidermis, Dermis und Subkutis — jede mit eigener Aufgabe.",
      bloodSupply: "Dermaler Gefäßplexus",
      funFact: "Ein einziger Quadratzentmeter kann Hunderte Schweißdrüsen und Meter von Blutgefäßen enthalten.",
      tissue: "Epidermisschichten",
      comparison: "Haut vs. Darm",
      conditions: ["Ekzem", "Schuppenflechte (Psoriasis)", "Melanom", "Akne vulgaris", "Wundrose (Zellulitis)", "Kontaktdermatitis", "Rosazea", "Weißfleckenkrankheit (Vitiligo)"],
      hotspots: [
        { id: "epidermis", label: "Epidermis", detail: "Äußere Schutzschicht", position: [-0.05, 0.88, 1.4], color: "#ee7c6a" },
        { id: "dermis", label: "Dermis", detail: "Nerven, Gefäße & Drüsen", position: [0.29, 0.05, 1.4], color: "#f2a33b" },
        { id: "hypodermis", label: "Subkutis", detail: "Fett und Isolierung", position: [-0.39, -1.15, 1.4], color: "#6393d8" },
        { id: "follicle", label: "Haarfollikel", detail: "Verankert jedes Haar", position: [0.89, -0.44, 1.4], color: "#d89bc4" },
      ],
    },
    ar: {
      name: "الجلد",
      scientificName: "Integumentum",
      system: "الجهاز الجلدي",
      description: "أكبر أعضاء الجسم — حاجز حي يشعر باللمس، ويحفظ الماء، وينظم درجة الحرارة.",
      poetic: "الحد الحي للجسم",
      size: "حوالي 2 متر مربع عند بسطه",
      weight: "3.5–5 كغم",
      location: "يغطي الجسم بأكمله",
      function: "الحماية، الإحساس، والتبريد",
      dailyFact: "يطرح حوالي 500 مليون خلية يومياً",
      medical: "ثلاث طبقات رئيسية — البشرة، الأدماء، وتحت الجلد — لكل منها وظيفة مميزة.",
      bloodSupply: "الضفيرة الوعائية الجلدية",
      funFact: "سنتيمتر مربع واحد يحتوي على مئات الغدد العرقية وأمتار من الأوعية الدموية.",
      tissue: "طبقات البشرة",
      comparison: "الجلد مقابل الأمعاء",
      conditions: ["الإكزيما", "الصدفية", "الميلانوما", "حب الشباب", "التهاب النسيج الخلوي", "التهاب الجلد التماسي", "الوردية", "البهاق"],
      hotspots: [
        { id: "epidermis", label: "البشرة", detail: "الطبقة الواقية الخارجية", position: [-0.05, 0.88, 1.4], color: "#ee7c6a" },
        { id: "dermis", label: "الأديم", detail: "الأعصاب والأوعية والغدد", position: [0.29, 0.05, 1.4], color: "#f2a33b" },
        { id: "hypodermis", label: "تحت الجلد", detail: "الدهون والعزل الحراري", position: [-0.39, -1.15, 1.4], color: "#6393d8" },
        { id: "follicle", label: "جريب الشعرة", detail: "يثبت كل شعرة", position: [0.89, -0.44, 1.4], color: "#d89bc4" },
      ],
    },
  },
  "nervous-system": {
    en: {
      name: "Nervous System",
      scientificName: "Systema nervosum",
      system: "Nervous System",
      description: "A vast network of neurons and supporting cells that transmits signals between the brain, spinal cord, and every corner of the body.",
      poetic: "The body's lightning network",
      size: "Brain + 45 m of nerve fibres",
      weight: "Approx. 2 kg (brain + cord + nerves)",
      location: "Brain, spinal cord, and throughout all tissues",
      function: "Senses, processes, and responds",
      dailyFact: "Sends about 100 billion neural signals",
      medical: "Impulses travel along myelinated fibres at up to 120 m/s.",
      bloodSupply: "Cerebral, spinal, and peripheral vascular networks",
      funFact: "Your nervous system can detect a single photon of light and a touch of just 20 milligrams.",
      tissue: "Neurones and glia",
      comparison: "Nervous system vs. brain",
      conditions: ["Multiple sclerosis", "Peripheral neuropathy", "Parkinson's disease", "Alzheimer's disease", "Epilepsy", "ALS", "Guillain-Barré syndrome", "Meningitis"],
      hotspots: [
        { id: "cerebrum", label: "Cerebrum", detail: "Conscious thought & movement", position: [0.0, 1.2, 0.6], color: "#9b7ec8" },
        { id: "spinal-cord", label: "Spinal Cord", detail: "Relay pathway", position: [0.0, -0.2, 0.2], color: "#c58696" },
        { id: "peripheral", label: "Peripheral Nerves", detail: "Body-wide signalling", position: [0.8, -1.0, 0.4], color: "#6393d8" },
        { id: "autonomic", label: "Autonomic Network", detail: "Controls involuntary functions", position: [-0.6, 0.1, 0.3], color: "#f2a33b" },
      ],
    },
    de: {
      name: "Nervensystem",
      scientificName: "Systema nervosum",
      system: "Nervensystem",
      description: "Ein riesiges Netzwerk aus Neuronen und Stützzellen, das Signale zwischen Gehirn, Rückenmark und allen Körperregionen überträgt.",
      poetic: "Das Blitznetzwerk des Körpers",
      size: "Gehirn + 45 m Nervenfasern",
      weight: "Ca. 2 kg (Gehirn + Mark + Nerven)",
      location: "Gehirn, Rückenmark und in allen Geweben",
      function: "Wahrnehmen, verarbeiten und reagieren",
      dailyFact: "Sendet rund 100 Milliarden Nervensignale",
      medical: "Impulse reisen entlang myelinisierter Fasern mit bis zu 120 m/s.",
      bloodSupply: "Zerebrale, spinale und periphere Gefäßnetze",
      funFact: "Das Nervensystem kann ein einzelnes Photon Licht und eine Berührung von nur 20 Milligramm wahrnehmen.",
      tissue: "Neuronen und Gliazellen",
      comparison: "Nervensystem vs. Gehirn",
      conditions: ["Multiple Sklerose", "Periphere Neuropathie", "Parkinson-Krankheit", "Alzheimer-Krankheit", "Epilepsie", "ALS", "Guillain-Barré-Syndrom", "Meningitis"],
      hotspots: [
        { id: "cerebrum", label: "Großhirn", detail: "Bewusstes Denken & Bewegung", position: [0.0, 1.2, 0.6], color: "#9b7ec8" },
        { id: "spinal-cord", label: "Rückenmark", detail: "Übertragungsweg", position: [0.0, -0.2, 0.2], color: "#c58696" },
        { id: "peripheral", label: "Periphere Nerven", detail: "Körperweite Signalübertragung", position: [0.8, -1.0, 0.4], color: "#6393d8" },
        { id: "autonomic", label: "Autonomes Nervensystem", detail: "Steuert unwillkürliche Funktionen", position: [-0.6, 0.1, 0.3], color: "#f2a33b" },
      ],
    },
    ar: {
      name: "الجهاز العصبي",
      scientificName: "Systema nervosum",
      system: "الجهاز العصبي",
      description: "شبكة واسعة من الخلايا العصبية والخلايا الداعمة تنقل الإشارات بين الدماغ والحبل الشوكي وسائر أنحاء الجسم.",
      poetic: "شبكة البرق في الجسم",
      size: "الدماغ + 45 متراً من الألياف العصبية",
      weight: "حوالي 2 كغم (دماغ + حبل + أعصاب)",
      location: "الدماغ والحبل الشوكي وجميع الأنسجة",
      function: "الإحساس والمعالجة والاستجابة",
      dailyFact: "يرسل نحو 100 مليار إشارة عصبية يومياً",
      medical: "تسير الإشارات عبر الألياف المغلفة بالميالين بسرعة تصل إلى 120 م/ث.",
      bloodSupply: "الشبكة الوعائية الدماغية والشوكية والطرفية",
      funFact: "يستطيع جهازك العصبي اكتشاف فوتون ضوئي واحد ولمسة خفيفة لا تتجاوز 20 ملغراماً.",
      tissue: "الخلايا العصبية والخلايا الدبقية",
      comparison: "الجهاز العصبي مقابل الدماغ",
      conditions: ["التصلب المتعدد", "الاعتلال العصبي المحيطي", "داء باركنسون", "داء الزهايمر", "الصرع", "التصلب الجانبي الضموري", "متلازمة غيلان-باريه", "التهاب السحايا"],
      hotspots: [
        { id: "cerebrum", label: "المخ الكبير", detail: "التفكير الواعي والحركة", position: [0.0, 1.2, 0.6], color: "#9b7ec8" },
        { id: "spinal-cord", label: "الحبل الشوكي", detail: "مسار نقل الإشارات", position: [0.0, -0.2, 0.2], color: "#c58696" },
        { id: "peripheral", label: "الأعصاب الطرفية", detail: "شبكة الإشارات على امتداد الجسم", position: [0.8, -1.0, 0.4], color: "#6393d8" },
        { id: "autonomic", label: "الجهاز العصبي اللاإرادي", detail: "يتحكم في الوظائف اللاإرادية", position: [-0.6, 0.1, 0.3], color: "#f2a33b" },
      ],
    },
  },
  "muscular-system": {
    en: {
      name: "Muscular System",
      scientificName: "Systema musculare",
      system: "Muscular System",
      description: "Over 600 muscles that generate force for movement, posture, heat production, and organ function throughout the body.",
      poetic: "The engine of motion",
      size: "Covers the entire body frame",
      weight: "About 40% of body weight",
      location: "From face to foot, layered over bone",
      function: "Movement, posture, and heat generation",
      dailyFact: "Uses 300+ muscles just to stand still",
      medical: "Skeletal, smooth, and cardiac muscle each have a unique microstructure.",
      bloodSupply: "Extensive arterial and capillary networks within muscle bellies",
      funFact: "The gluteus maximus is the largest muscle; the stapedius in the ear is the smallest.",
      tissue: "Skeletal muscle fibres",
      comparison: "Muscular system vs. skeleton",
      conditions: ["Muscular dystrophy", "Myasthenia gravis", "Rhabdomyolysis", "Fibromyalgia", "Compartment syndrome", "Muscle strain", "Myopathy", "Tendinopathy"],
      hotspots: [
        { id: "deltoid", label: "Deltoid", detail: "Shoulder abductor", position: [-0.9, 1.0, 0.5], color: "#c05c5c" },
        { id: "pectoralis", label: "Pectoralis Major", detail: "Chest power muscle", position: [0.0, 0.8, 0.8], color: "#f2a33b" },
        { id: "quadriceps", label: "Quadriceps", detail: "Knee extensor group", position: [0.4, -1.2, 0.6], color: "#6393d8" },
        { id: "gluteus", label: "Gluteus Maximus", detail: "Largest muscle in the body", position: [-0.3, -0.7, -0.5], color: "#d89bc4" },
      ],
    },
    de: {
      name: "Muskelsystem",
      scientificName: "Systema musculare",
      system: "Muskelsystem",
      description: "Über 600 Muskeln erzeugen Kraft für Bewegung, Haltung, Wärmeproduktion und Organfunktionen im gesamten Körper.",
      poetic: "Der Motor der Bewegung",
      size: "Bedeckt den gesamten Körperrahmen",
      weight: "Etwa 40 % des Körpergewichts",
      location: "Von Kopf bis Fuß über dem Knochen geschichtet",
      function: "Bewegung, Haltung und Wärmeproduktion",
      dailyFact: "Verwendet über 300 Muskeln allein zum Stehen",
      medical: "Skelett-, glatte und Herzmuskulatur haben jeweils eine einzigartige Mikrostruktur.",
      bloodSupply: "Ausgedehnte Arterien- und Kapillarnetzwerke in den Muskelbäuchen",
      funFact: "Der Musculus gluteus maximus ist der größte Muskel; der Musculus stapedius im Ohr ist der kleinste.",
      tissue: "Skelettmuskelfasern",
      comparison: "Muskelsystem vs. Skelett",
      conditions: ["Muskeldystrophie", "Myasthenia gravis", "Rhabdomyolyse", "Fibromyalgie", "Kompartmentsyndrom", "Muskelzerrung", "Myopathie", "Tendinopathie"],
      hotspots: [
        { id: "deltoid", label: "Deltamuskel", detail: "Schulterabduktor", position: [-0.9, 1.0, 0.5], color: "#c05c5c" },
        { id: "pectoralis", label: "Großer Brustmuskel", detail: "Kraftmuskel der Brust", position: [0.0, 0.8, 0.8], color: "#f2a33b" },
        { id: "quadriceps", label: "Quadrizeps", detail: "Kniestreckende Muskelgruppe", position: [0.4, -1.2, 0.6], color: "#6393d8" },
        { id: "gluteus", label: "Großer Gesäßmuskel", detail: "Größter Muskel des Körpers", position: [-0.3, -0.7, -0.5], color: "#d89bc4" },
      ],
    },
    ar: {
      name: "الجهاز العضلي",
      scientificName: "Systema musculare",
      system: "الجهاز العضلي",
      description: "أكثر من 600 عضلة تولّد القوة اللازمة للحركة والوضعية وإنتاج الحرارة ووظائف الأعضاء في جميع أنحاء الجسم.",
      poetic: "محرك الحركة",
      size: "يغطي هيكل الجسم بأكمله",
      weight: "حوالي 40% من وزن الجسم",
      location: "من الوجه إلى القدم، فوق العظام بطبقات",
      function: "الحركة، الوضعية، وتوليد الحرارة",
      dailyFact: "يستخدم أكثر من 300 عضلة لمجرد الوقوف",
      medical: "العضلات الهيكلية والملساء والقلبية لها بنية مجهرية مميزة لكل منها.",
      bloodSupply: "شبكات شريانية وشعرية واسعة داخل أجسام العضلات",
      funFact: "العضلة الألوية الكبرى هي أكبر عضلة في الجسم؛ والعضلة الركابية في الأذن هي الأصغر.",
      tissue: "ألياف العضلات الهيكلية",
      comparison: "الجهاز العضلي مقابل الهيكل العظمي",
      conditions: ["ضمور العضلات", "الوهن العضلي الوبيل", "انحلال الربيدات العضلية", "الفيبروميالجيا", "متلازمة الحجرة", "إجهاد العضلات", "اعتلال العضلات", "التهاب الأوتار"],
      hotspots: [
        { id: "deltoid", label: "العضلة الدالية", detail: "مبعِّد مفصل الكتف", position: [-0.9, 1.0, 0.5], color: "#c05c5c" },
        { id: "pectoralis", label: "العضلة الصدرية الكبرى", detail: "عضلة القوة الصدرية", position: [0.0, 0.8, 0.8], color: "#f2a33b" },
        { id: "quadriceps", label: "العضلة رباعية الرؤوس", detail: "مجموعة باسطة الركبة", position: [0.4, -1.2, 0.6], color: "#6393d8" },
        { id: "gluteus", label: "العضلة الألوية الكبرى", detail: "أكبر عضلة في الجسم", position: [-0.3, -0.7, -0.5], color: "#d89bc4" },
      ],
    },
  },
  skeleton: {
    en: {
      name: "Skeleton",
      scientificName: "Systema skeletale",
      system: "Skeletal System",
      description: "A living framework of 206 bones that supports the body, protects vital organs, enables movement, and produces blood cells.",
      poetic: "The architecture of life",
      size: "About 1.7–1.8 m (full adult height)",
      weight: "About 15% of body weight (approx. 10–12 kg)",
      location: "Interior framework of the entire body",
      function: "Support, protection, and movement",
      dailyFact: "Produces ~2 million red blood cells every second",
      medical: "Bone is a dynamic tissue, constantly remodelled by osteoblasts and osteoclasts.",
      bloodSupply: "Periosteal and medullary arteries feeding each bone",
      funFact: "Babies are born with around 270 bones; many fuse together so adults end up with 206.",
      tissue: "Compact and spongy bone",
      comparison: "Skeleton vs. muscular system",
      conditions: ["Osteoporosis", "Osteoarthritis", "Rheumatoid arthritis", "Rickets", "Osteosarcoma", "Paget's disease", "Scoliosis", "Stress fractures"],
      hotspots: [
        { id: "skull", label: "Skull", detail: "Protects the brain", position: [0.0, 2.0, 0.3], color: "#a09070" },
        { id: "spine", label: "Vertebral Column", detail: "Supports and transmits load", position: [0.0, 0.4, 0.1], color: "#c69a5e" },
        { id: "femur", label: "Femur", detail: "Longest and strongest bone", position: [0.3, -1.0, 0.4], color: "#f2a33b" },
        { id: "sternum", label: "Sternum", detail: "Anchors the rib cage", position: [0.0, 0.9, 0.7], color: "#6393d8" },
      ],
    },
    de: {
      name: "Skelett",
      scientificName: "Systema skeletale",
      system: "Skelettsystem",
      description: "Ein lebendiges Gerüst aus 206 Knochen, das den Körper stützt, lebenswichtige Organe schützt, Bewegung ermöglicht und Blutzellen produziert.",
      poetic: "Die Architektur des Lebens",
      size: "Etwa 1,7–1,8 m (ausgewachsene Körpergröße)",
      weight: "Ca. 15 % des Körpergewichts (ca. 10–12 kg)",
      location: "Inneres Rahmenwerk des gesamten Körpers",
      function: "Stützung, Schutz und Bewegung",
      dailyFact: "Produziert ca. 2 Millionen rote Blutkörperchen pro Sekunde",
      medical: "Knochen ist ein dynamisches Gewebe, das ständig von Osteoblasten und Osteoklasten umgebaut wird.",
      bloodSupply: "Periostale und medulläre Arterien versorgen jeden Knochen",
      funFact: "Babys werden mit etwa 270 Knochen geboren; viele verschmelzen, sodass Erwachsene 206 haben.",
      tissue: "Kompakter und spongiöser Knochen",
      comparison: "Skelett vs. Muskelsystem",
      conditions: ["Osteoporose", "Arthrose", "Rheumatoide Arthritis", "Rachitis", "Osteosarkom", "Paget-Krankheit", "Skoliose", "Ermüdungsfrakturen"],
      hotspots: [
        { id: "skull", label: "Schädel", detail: "Schützt das Gehirn", position: [0.0, 2.0, 0.3], color: "#a09070" },
        { id: "spine", label: "Wirbelsäule", detail: "Trägt und überträgt Last", position: [0.0, 0.4, 0.1], color: "#c69a5e" },
        { id: "femur", label: "Oberschenkelknochen", detail: "Längster und stärkster Knochen", position: [0.3, -1.0, 0.4], color: "#f2a33b" },
        { id: "sternum", label: "Brustbein", detail: "Befestigt den Brustkorb", position: [0.0, 0.9, 0.7], color: "#6393d8" },
      ],
    },
    ar: {
      name: "الهيكل العظمي",
      scientificName: "Systema skeletale",
      system: "الجهاز الهيكلي",
      description: "إطار حي مكوّن من 206 عظمة يدعم الجسم ويحمي الأعضاء الحيوية ويُتيح الحركة وينتج خلايا الدم.",
      poetic: "هندسة الحياة",
      size: "حوالي 1.7–1.8 متر (الطول الكامل للبالغ)",
      weight: "حوالي 15% من وزن الجسم (نحو 10–12 كغم)",
      location: "الإطار الداخلي للجسم بأكمله",
      function: "الدعم والحماية والحركة",
      dailyFact: "ينتج حوالي 2 مليون كرية دم حمراء في الثانية الواحدة",
      medical: "العظم نسيج حي يُعاد تشكيله باستمرار بفعل الخلايا العظمية البانية والهادمة.",
      bloodSupply: "الشرايين السمحاقية والنخاعية التي تغذي كل عظمة",
      funFact: "يولد الأطفال بحوالي 270 عظمة، ثم تندمج كثيرها ليصل عدد عظام البالغين إلى 206.",
      tissue: "العظم القشري والعظم الإسفنجي",
      comparison: "الهيكل العظمي مقابل الجهاز العضلي",
      conditions: ["هشاشة العظام", "التهاب المفاصل التنكسي", "التهاب المفاصل الروماتويدي", "الكساح", "ساركوما العظم", "مرض باجيت", "الجنف", "كسور الإجهاد"],
      hotspots: [
        { id: "skull", label: "الجمجمة", detail: "تحمي الدماغ", position: [0.0, 2.0, 0.3], color: "#a09070" },
        { id: "spine", label: "العمود الفقري", detail: "يدعم الجسم وينقل الأحمال", position: [0.0, 0.4, 0.1], color: "#c69a5e" },
        { id: "femur", label: "عظم الفخذ", detail: "أطول وأقوى عظمة في الجسم", position: [0.3, -1.0, 0.4], color: "#f2a33b" },
        { id: "sternum", label: "عظمة القص", detail: "تثبت القفص الصدري", position: [0.0, 0.9, 0.7], color: "#6393d8" },
      ],
    },
  },
};

const baseOrganMetadata: Record<OrganId, { model: string; icon: string; accent: string; illustrated: boolean }> = {
  heart: { model: "/models/heart.glb", icon: "♥", accent: "#ee7c6a", illustrated: true },
  brain: { model: "/models/brain.glb", icon: "◉", accent: "#c58696", illustrated: true },
  lungs: { model: "/models/lungs.glb", icon: "◍", accent: "#dd8f8b", illustrated: true },
  liver: { model: "/models/liver.glb", icon: "≈", accent: "#b86858", illustrated: true },
  kidneys: { model: "/models/kidneys.glb", icon: "∞", accent: "#c96963", illustrated: true },
  eyeball: { model: "/models/eyeball.glb", icon: "⊙", accent: "#7294b9", illustrated: true },
  intestine: { model: "/models/intestine.glb", icon: "§", accent: "#d78b77", illustrated: true },
  pancreas: { model: "/models/pancreas.glb", icon: "◈", accent: "#c69a5e", illustrated: true },
  skin: { model: "/models/skin.glb", icon: "▦", accent: "#c99277", illustrated: true },
  "nervous-system": { model: "procedural:nervous-system", icon: "⚡", accent: "#9b7ec8", illustrated: true },
  "muscular-system": { model: "procedural:muscular-system", icon: "⊕", accent: "#c05c5c", illustrated: true },
  skeleton: { model: "procedural:skeleton", icon: "✦", accent: "#a09070", illustrated: true },
};

export const organIds: OrganId[] = [
  "heart",
  "brain",
  "lungs",
  "liver",
  "kidneys",
  "eyeball",
  "intestine",
  "pancreas",
  "skin",
  "nervous-system",
  "muscular-system",
  "skeleton",
];

export function getOrgans(lang: Language = "en"): Organ[] {
  return organIds.map((id) => {
    const meta = baseOrganMetadata[id];
    const trans = organTranslations[id][lang] || organTranslations[id]["en"];
    return {
      id,
      ...meta,
      ...trans,
    };
  });
}

export function getOrganById(id: OrganId, lang: Language = "en"): Organ {
  const meta = baseOrganMetadata[id];
  const trans = organTranslations[id][lang] || organTranslations[id]["en"];
  return {
    id,
    ...meta,
    ...trans,
  };
}

/** Backwards-compatible default list (English) */
export const organs: Organ[] = getOrgans("en");

export const organById = Object.fromEntries(organs.map((organ) => [organ.id, organ])) as Record<OrganId, Organ>;
